name: Update Blacklist AGH

       # Controls when the workflow will run
on:
  push:
    paths-ignore:
    - '.github/**'
  schedule:
    - cron: '0 16 * * *'

jobs:
  # This workflow contains a single job called "cron"
  cron:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3

      - name: Build blocklist
        uses: actions/checkout@v3
      - run: |
          npm i -g @adguard/hostlist-compiler
          hostlist-compiler -c configuration1.json -o blocklist-agh.txt
          npm i -g @adguard/hostlist-compiler
          hostlist-compiler -c configuration2.json -o adultfilter-agh.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "AGH"
          git push
