name: PyFunceble
on:
  push:
    paths-ignore:
    - '.github/**'

  schedule:
    - cron: '0 0 * * *'

jobs:
  build-blocklist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3

      - name: Build blocklist
        uses: actions/checkout@v3
      - rame: Install dependencies
        run: |
        pip install --pre PyFunceble

    - name: Get PyFunceble version
        run: |
        PyFunceble --version

    - name: Run PyFunceble
        run: |
        PyFunceble -a --ci -dns 9.9.9.10:53 149.112.112.10:53 -f blocklist.txt --plain
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "update blacklist"
          git push
	  
