name: Update Blacklist AGH
on:
  push:
    paths-ignore:
    - '.github/**'
    - 'README.md'
  schedule:
    - cron: '0 12 * * *'

jobs:
  build-blocklist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3

      - name: Build blocklist
        uses: actions/checkout@v3
      - run: |
          yarn add @adguard/hostlist-compiler
          hostlist-compiler -c configuration1.json -o blocklist-agh.txt
          yarn add @adguard/hostlist-compiler
          hostlist-compiler -c configuration2.json -o whitelist-agh.txt
          yarn add @adguard/hostlist-compiler
          hostlist-compiler -c configuration3.json -o adultfilter-agh.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "update blacklist"
          git push
