name: PyFunceble
on:
  push:
    paths-ignore:
    - '.github/**'
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python V2
        uses: actions/setup-python@v2
        with:
          python-version: '2.x'
          architecture: 'x64'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install domain2idna
          pip install PyFunceble
          PyFunceble -a --ci --logging-level critical -f blocklist.txt --plain
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "PyFunceble"
          git push
